# Generated by Django 3.2.6 on 2021-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_alias', models.CharField(max_length=255, unique=True)),
                ('db_name', models.CharField(max_length=100)),
                ('db_engine', models.CharField(default='postgresql', max_length=100)),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_user', models.CharField(default='postgres', max_length=100)),
                ('db_password', models.CharField(default='root', max_length=100)),
                ('db_port', models.CharField(default='5432', max_length=100)),
                ('school_code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
