# Generated by Django 3.2.6 on 2021-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdb',
            name='school_code',
        ),
        migrations.AddField(
            model_name='clientdb',
            name='code',
            field=models.CharField(default='tir', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
