# Generated by Django 3.2.6 on 2021-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210815_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdb',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
