# Generated by Django 3.2.6 on 2021-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clientdb_db_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdb',
            name='image',
            field=models.FileField(default='lala.png', upload_to='cooo'),
        ),
    ]
